from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ix_fusion.vnext import GATES, SOLVERS, load_seed_league

seeds = load_seed_league(ROOT / "configs" / "vnext" / "seed_league.json")
report = {
    "candidate_families": [seed.family_id for seed in seeds],
    "promotion_gates": [gate.gate_id for gate in GATES],
    "local_solver_availability": {solver.name: solver.locally_available() for solver in SOLVERS},
    "claim": "Architecture readiness only. No high-fidelity fusion-performance claim is generated by this report."
}
print(json.dumps(report, indent=2, sort_keys=True))
