from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

from .analysis import evaluate_candidate
from .claims import evaluate_reduced_gates
from .config import load_candidate, load_json
from .evidence import evidence_bundle, write_json
from .external import detect_external_solvers
from .figures import plot_metric_comparison, plot_poincare, plot_rf_robustness
from .optimizer import optimize_seed
from .report import metrics_dict, render_poc_markdown, write_markdown
from .rf import monte_carlo_robustness


MODEL_NAME = "IX-Fusion reduced Hamiltonian/field-strength screening model v0.1"


def run_poc(repo_root: Path, output_root: Path | None = None, generate_figures: bool = True) -> dict:
    repo_root = repo_root.resolve()
    if output_root is None:
        output_root = repo_root / "results"
    output_root.mkdir(parents=True, exist_ok=True)
    candidate_path = repo_root / "configs/candidates/c6_seed.json"
    baseline_path = repo_root / "configs/baselines/matched_helical_5fp.json"
    opt_path = repo_root / "configs/optimization/poc_optimizer.json"
    candidate_seed = load_candidate(candidate_path)
    baseline_seed = load_candidate(baseline_path)
    opt = load_json(opt_path)
    candidate, candidate_history = optimize_seed(
        candidate_seed,
        passes=int(opt["passes"]),
        amplitude_step=float(opt["amplitude_step"]),
        phase_step=float(opt["phase_step_radians"]),
        iota_step=float(opt["iota_step"]),
        mirror_step=float(opt["mirror_step"]),
    )
    baseline, baseline_history = optimize_seed(
        baseline_seed,
        passes=int(opt["passes"]),
        amplitude_step=float(opt["amplitude_step"]),
        phase_step=float(opt["phase_step_radians"]),
        iota_step=float(opt["iota_step"]),
        mirror_step=float(opt["mirror_step"]),
    )
    candidate_metrics = evaluate_candidate(candidate)
    baseline_metrics = evaluate_candidate(baseline)
    external = detect_external_solvers()
    verdict = evaluate_reduced_gates(candidate_metrics, baseline_metrics, external)
    rf_cfg = load_json(repo_root / "configs/system/rf_robustness.json")
    robustness = monte_carlo_robustness(**rf_cfg)

    poc_dir = output_root / "poc"
    baseline_dir = output_root / "baselines"
    evidence_dir = output_root / "evidence"
    figure_dir = output_root / "figures"
    poc_dir.mkdir(parents=True, exist_ok=True)
    baseline_dir.mkdir(parents=True, exist_ok=True)
    evidence_dir.mkdir(parents=True, exist_ok=True)

    candidate_payload = {
        "seed": candidate_seed.to_dict(),
        "optimized": candidate.to_dict(),
        "optimizer_history": candidate_history,
        "metrics": metrics_dict(candidate_metrics),
    }
    baseline_payload = {
        "seed": baseline_seed.to_dict(),
        "optimized": baseline.to_dict(),
        "optimizer_history": baseline_history,
        "metrics": metrics_dict(baseline_metrics),
    }
    verdict_payload = asdict(verdict)
    robustness_payload = asdict(robustness)
    write_json(poc_dir / "c6_candidate.json", candidate_payload)
    write_json(baseline_dir / "matched_helical_5fp.json", baseline_payload)
    write_json(poc_dir / "verdict.json", verdict_payload)
    write_json(output_root / "monte_carlo/rf_robustness.json", robustness_payload)
    report = render_poc_markdown(
        candidate,
        baseline,
        candidate_metrics,
        baseline_metrics,
        verdict,
        robustness,
    )
    write_markdown(poc_dir / "POC_RESULT.md", report)

    assumptions = [
        "All magnetic quantities in the internal model are dimensionless screening quantities.",
        "The reduced field-line equations are not derived from a solved MHD equilibrium.",
        "The bounce-action metric is a comparative proxy, not the second adiabatic invariant of a solved equilibrium.",
        "The candidate and matched baseline receive the same deterministic optimizer budget.",
        "RF Monte Carlo models spatial-mode purity only and does not model plasma-wave coupling.",
    ]
    limitations = [
        "No DESC, VMEC, or equivalent equilibrium has been generated by the internal POC.",
        "No SIMSOPT or equivalent coil realization has been generated by the internal POC.",
        "No finite-beta MHD stability, gyrokinetic turbulence, neutronics, tritium breeding, divertor, or net-electric calculation is performed.",
        "Engineering metrics are normalized screening proxies and are not structural, thermal, nuclear, or cryogenic certification calculations.",
    ]
    bundle = evidence_bundle(
        run_id="IXFUSION-POC-001",
        model=MODEL_NAME,
        seed=int(rf_cfg["seed"]),
        config_paths=[candidate_path, baseline_path, opt_path, repo_root / "configs/system/rf_robustness.json"],
        outputs={
            "candidate": candidate_payload,
            "baseline": baseline_payload,
            "verdict": verdict_payload,
            "rf_robustness": robustness_payload,
            "external_solver_status": [asdict(s) for s in external],
        },
        assumptions=assumptions,
        limitations=limitations,
    )
    write_json(evidence_dir / "IXFUSION-POC-001.json", bundle)

    if generate_figures:
        plot_poincare(candidate, figure_dir / "c6_poincare.png")
        plot_poincare(baseline, figure_dir / "baseline_poincare.png")
        plot_metric_comparison(candidate_metrics, baseline_metrics, figure_dir / "poc_metric_comparison.png")
        plot_rf_robustness(robustness, figure_dir / "rf_robustness.png")

    return {
        "candidate": candidate_payload,
        "baseline": baseline_payload,
        "verdict": verdict_payload,
        "rf_robustness": robustness_payload,
        "evidence": bundle,
    }
